// Generated by `npm run gen:types` — do not hand-edit.
// (Initial version written to match supabase/migrations; regenerate once the project is linked.)

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      cards: {
        Row: {
          card_number: string
          cert_number: string | null
          created_at: string
          estimated_value: number | null
          grade: string | null
          grade_company: string | null
          id: string
          insert_name: string | null
          is_auto: boolean
          is_graded: boolean
          is_patch: boolean
          is_relic: boolean
          is_rookie: boolean
          parallel: string | null
          player: string
          print_run: number | null
          purchase_date: string | null
          purchase_price: number | null
          quantity: number
          raw_condition: string | null
          serial_number: number | null
          set_name: string
          sold_date: string | null
          sold_price: number | null
          sport: string
          team: string | null
          updated_at: string
          user_id: string
          year: string
        }
        Insert: {
          card_number: string
          cert_number?: string | null
          created_at?: string
          estimated_value?: number | null
          grade?: string | null
          grade_company?: string | null
          id?: string
          insert_name?: string | null
          is_auto?: boolean
          is_graded?: boolean
          is_patch?: boolean
          is_relic?: boolean
          is_rookie?: boolean
          parallel?: string | null
          player: string
          print_run?: number | null
          purchase_date?: string | null
          purchase_price?: number | null
          quantity?: number
          raw_condition?: string | null
          serial_number?: number | null
          set_name: string
          sold_date?: string | null
          sold_price?: number | null
          sport: string
          team?: string | null
          updated_at?: string
          user_id?: string
          year: string
        }
        Update: {
          card_number?: string
          cert_number?: string | null
          created_at?: string
          estimated_value?: number | null
          grade?: string | null
          grade_company?: string | null
          id?: string
          insert_name?: string | null
          is_auto?: boolean
          is_graded?: boolean
          is_patch?: boolean
          is_relic?: boolean
          is_rookie?: boolean
          parallel?: string | null
          player?: string
          print_run?: number | null
          purchase_date?: string | null
          purchase_price?: number | null
          quantity?: number
          raw_condition?: string | null
          serial_number?: number | null
          set_name?: string
          sold_date?: string | null
          sold_price?: number | null
          sport?: string
          team?: string | null
          updated_at?: string
          user_id?: string
          year?: string
        }
        Relationships: []
      }
    }
    Views: { [_ in never]: never }
    Functions: { [_ in never]: never }
    Enums: { [_ in never]: never }
    CompositeTypes: { [_ in never]: never }
  }
}
